name: jhu-ncov
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.6
  - conda-forge::biopython=1.79
  - pysam=0.16
  - pandas
  - numpy
  - requests=2.23.0
  - snp-sites=2.5.1
  - snpeff=4.3.1t
  - seqtk=1.3
  - xorg-libxtst=1.2.3
  - xorg-libxrender
  - xorg-libxi
  - imagemagick
  - hdf5
  - nano
  - gawk
  - r-knitr
  - r-kableExtra
  - r-pander
  - r-pheatmap
  - r-ggplot2
  - r-broom
  - r-devtools
  - r-tidyverse
  - r-jsonlite
  - r-png
  - r-gridExtra
  - r-RColorBrewer
  - r-viridis
  - r-magick=2.7.3
  - r-rjson
  - r-ggextra
  - r-vcfr
  - bioconductor-gviz
  - bioconductor-rtracklayer
  - bioconductor-trackViewer
  - mafft
  - pip
  - pip:
    - git+https://github.com/nanoporetech/ont_fast5_api
    - pyvcf==